# Generated by Django 6.0.3 on 2026-03-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(db_index=True, max_length=100, verbose_name='Ресурс')),
                ('action', models.CharField(db_index=True, max_length=50, verbose_name='Действие')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Разрешение',
                'verbose_name_plural': 'Разрешения',
                'unique_together': {('resource', 'action')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название роли')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='app.actionpermission', verbose_name='Разрешения')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='app.role', verbose_name='Роли'),
        ),
    ]
